name: CI Back-end

on: 
    push: 

jobs:
    primeiro-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Primeiro passo"
            - name: Checkout
              uses: actions/checkout@v4
            - name: Listar arquivos
              run: ls ${{ github.workspace }}
            - name: Status
              run: echo "Status ${{ job.status }}"
